AWSTemplateFormatVersion: '2010-09-09'
Description: 'College HQ User Profile DynamoDB Table'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: Environment name

Resources:
  # Users table with Cognito sub as primary key
  CollegeHQUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'college-hq-users-${Environment}'
      BillingMode: PAY_PER_REQUEST  # On-demand billing
      AttributeDefinitions:
        - AttributeName: userId  # Cognito sub (UUID)
          AttributeType: S
        - AttributeName: email   # For secondary lookups
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH  # Primary key
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: 'CollegeHQ'

Outputs:
  UsersTableName:
    Description: 'Name of the Users DynamoDB table'
    Value: !Ref CollegeHQUsersTable
    Export:
      Name: !Sub '${AWS::StackName}-UsersTableName'
      
  UsersTableArn:
    Description: 'ARN of the Users DynamoDB table'
    Value: !GetAtt CollegeHQUsersTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UsersTableArn'